import "./globals.css";
import localFont from "next/font/local";
import Footer from "./components/Footer";
import About from "./components/About";
import Blocks from "./components/Blocks";
import Status from "./components/Status";

const sFFont = localFont({
  src: "./SFPRODISPLAYMEDIUM.otf",
  weight: "500",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="min-h-screen overflow-x-hidden scroll-smooth text-emerald-400 antialiased"
    >
      <body className={sFFont.className}>
        <main className="mx-3 flex max-w-5xl flex-col">
          <header className="h-12 md:h-36"></header>
          <About />
          <Status />
          <hr className="my-5 h-[1px] w-full border-0 bg-slate-800" />
          <Blocks />
          <div className="my-8 flex-1 overflow-hidden text-base">
            {children}
          </div>
          <hr className="h-[1px] w-full border-0 bg-slate-800" />
          <Footer />
        </main>
      </body>
    </html>
  );
}
