import Footer from './components/Footer'
import Navbar from './components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + 'flex w-7/12 m-auto min-h-screen flex-col items-baseline relative border-2 border-red-600'}>
        <Navbar />
        <div className='flex-1'>
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
