import "./globals.scss";
import { Recursive } from "next/font/google";
import Footer from "./components/Footer";
import About from "./components/About";
import Navbar from "./components/Navbar";
import Transition from "./components/Transition";
import { NavProvider } from "./Context/navigation";

const recursive = Recursive({ subsets: ["latin"] });

const bodyStyle = `${recursive.className} flex justify-center min-h-screen`;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className="tracking min-h-screen overflow-x-hidden scroll-smooth text-emerald-400 antialiased"
    >
      <body className={bodyStyle}>
        <main className="mx-3 flex max-w-5xl flex-col">
          <header className="h-12 md:h-24"></header>
          <NavProvider>
            <About />
            <hr className="my-5 h-[1px] w-full border-0 bg-stone-800" />
            <Navbar />
          </NavProvider>
          <Transition>{children}</Transition>
          <hr className="h-[1px] w-full border-0 bg-stone-800" />
          <Footer />
        </main>
      </body>
    </html>
  );
}
